### ISSUE TITLE
[ALBERT]error "expected str instance, bytes found" to error "list index out of range"

### ISSUE THREAD

**Issue by zsweet** [google-research/ALBERT#96] opened 2019-11-03 17:13 UTC
when i run run_squad_sp.py , error occur :
```
Traceback (most recent call last):
  File "run_squad_sp.py", line 1350, in <module>
    tf.app.run()
  File "/usr/local/app/.conda/envs/convlab/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_squad_sp.py", line 1257, in main
    output_fn=train_writer.process_feature)
  File "run_squad_sp.py", line 396, in convert_examples_to_features
    tok_cat_text = "".join(para_tokens).replace(
TypeError: sequence item 89: expected str instance, bytes found
```
and i find that the para_tokens as below:
```
['▁greece', '▁attract', 's', '▁more', '▁than', '▁16', '▁million', '▁tourists', '▁each', '▁year', ',', '▁thus', '▁contributing', '▁18', '.', '2%', '▁to', '▁the', '▁nation', "'", 's', '▁gdp', '▁in', '▁2008', '▁according', '▁to', '▁an', '▁', 'oe', 'cd', '▁report', '.', '▁the', '▁same', '▁survey', '▁showed', '▁that', '▁the', '▁average', '▁tourist', '▁expenditure', '▁while', '▁in', '▁greece', '▁was', '▁$1', ',', '07', '3', ',', '▁ranking', '▁greece', '▁10', 'th', '▁in', '▁the', '▁world', '.', '▁the', '▁number', '▁of', '▁jobs', '▁directly', '▁or', '▁indirectly', '▁related', '▁to', '▁the', '▁tourism', '▁sector', '▁were', '▁8', '40,000', '▁in', '▁2008', '▁and', '▁represented', '▁', '19%', '▁of', '▁the', '▁country', "'", 's', '▁total', '▁labor', '▁force', '.', '▁in', "b'\\xe2\\x96\\x812009'", ',', '▁greece', '▁welcomed', '▁over', '▁19', '.', '3', '▁million', '▁tourists', ',', '▁a', '▁major', '▁increase', '▁from', '▁the', '▁17', '.', '7', '▁million', '▁tourists', '▁the', '▁country', '▁welcomed', '▁in', '▁2008', '.']
```
so i modify my code from ` tok_cat_text = "".join(para_tokens).replace(tokenization.SPIECE_UNDERLINE.decode("utf-8"), " ")` to`tok_cat_text = "".join([w.decode() if type(w)==bytes else w for w in para_tokens]).replace(  tokenization.SPIECE_UNDERLINE.decode("utf-8"), " ")` and another error occurs as below:
```
Traceback (most recent call last):
  File "run_squad_sp.py", line 1350, in <module>
    tf.app.run()
  File "/usr/local/app/.conda/envs/convlab/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_squad_sp.py", line 1257, in main
    output_fn=train_writer.process_feature)
  File "run_squad_sp.py", line 471, in convert_examples_to_features
    n, is_start=False)
  File "run_squad_sp.py", line 316, in _convert_index
    if index[pos] is not None:
IndexError: list index out of range
```
what's wrong with it？ thx

**Comment by 0x0539** [comment] 2020-01-08 23:00
This should no longer be an issue in the new `run_squad_v1.py` and `run_squad_v2.py` scripts. It was caused by a (required) PY2->PY3 code migration. Apologies for the inconvenience

Closing for now. Please reopen if you still have this issue with the new scripts.

**Closed by 0x0539** 2020-01-08 23:00 UTC
