### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: Graph ops missing from the python registry ({'Einsum'}) are also absent from the c++ registry

### ISSUE THREAD

**Issue by ntaherkhani** [google-research/ALBERT#82] opened 2019-11-15 21:56 UTC
I am trying to creat tensorflow-hub Module using locally saved ALBER pre-trained model and I am getting this error :
tensorflow.python.framework.errors_impl.NotFoundError: Graph ops missing from the python registry ({'Einsum'}) are also absent from the c++ registry.
I have:
tensorflow: 1.14.0
tensorflow-hub: 0.7.0
opt-einsum= 3.1.0
I am working on MAC OS High Sierra 10.13.6

**Comment by vilas4485** [comment] 2020-01-07 06:23
Can you please upgrade to Tensorflow (-gpu) 1.15, as specified in the requirements.txt? Thanks

**Comment by 0x0539** [comment] 2020-01-08 22:39
Duplicate of #112 

See the Jan 7 update in the readme.

**Closed by 0x0539** 2020-01-08 22:39 UTC

**Comment by 0x0539** [comment] 2020-01-08 23:06
Duplicate of #94
