### ISSUE TITLE
Is it possible to reload a pretrained tfhub albert in tf2.0?

### ISSUE THREAD

**Issue by mcggood** [google-research/ALBERT#11] opened 2019-12-12 09:16 UTC
for example:
ALBERT_PATH = "xxx"   // a pretrained tfhub albert model
albert_layer = hub.KerasLayer(ALBERT_PATH , trainable=True)

**Comment by Tony-Y** [comment] 2019-12-23 07:52
https://github.com/kpe/bert-for-tf2

**Comment by Tony-Y** [comment] 2019-12-24 07:40
```python
albert_layer = hub.KerasLayer("https://tfhub.dev/google/albert_xxlarge/2",
    trainable=True, signature='tokens', signature_outputs_as_dict=True)
input_ids = tf.keras.layers.Input(shape=(max_seq_length,),
                                  dtype=tf.int32, name="input_ids")
input_mask = tf.keras.layers.Input(shape=(max_seq_length,),
                                   dtype=tf.int32, name="input_mask")
segment_ids = tf.keras.layers.Input(shape=(max_seq_length,),
                                    dtype=tf.int32, name="segment_ids")
albert_inputs = [input_ids, input_mask, segment_ids]
outputs = albert_layer(inputs=dict(
      input_ids=input_ids,
      input_mask=input_mask,
      segment_ids=segment_ids,
    ))
```

**Comment by xincui-math** [comment] 2020-01-03 01:41
I think the short answer is nope you can't.

1. You could load using tfhub however all parameters are not trainable as mentioned by Tony-Y.

2. (https://github.com/google-research/ALBERT/blob/master/modeling.py) need to be modified as
```
from tensorflow.contrib import layers as contrib_layers
```
won't work.

**Comment by 0x0539** [comment] 2020-01-08 21:49
Sorry for the delayed response. This looks like a duplicate of #112
We only support ALBERT on TF1.15 at this time. We haven't really tested ALBERT in TF2.0 and don't have plans to release a TF2.0-compatible version of ALBERT modules (yet).

**Closed by 0x0539** 2020-01-08 21:49 UTC
