### ISSUE TITLE
LookupError: No gradient defined for operation 'module_apply_tokens/bert/encoder/transformer/group_0_11/layer_11/inner_group_0/ffn_1/intermediate/output/dense/einsum/Ein$um' (op type: Einsum)

### ISSUE THREAD

**Issue by agupta74** [google-research/ALBERT#31] opened 2019-12-19 07:10 UTC
Please refer to the link https://github.com/google-research/google-research/issues/108 for more details on this issue.

**Comment by 0x0539** [comment] 2019-12-20 23:19
Tentatively closing this issue. See [google-research/google-research#108](https://github.com/google-research/google-research/issues/108) for the resolution.

**Comment by 0x0539** [comment] 2020-01-06 16:29
I'll close this when the new TFHub v2 modules and checkpoints are released.

**Comment by 0x0539** [comment] 2020-01-08 21:54
Duplicate of #94

**Closed by 0x0539** 2020-01-08 21:54 UTC
